# God help me I'm not good with CI

name: Compile

on:
  pull_request:
    branches: master
  push:
    branches:
      - master
      - ci_testing

jobs:
  lint:
    name: SpacemanDMM
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache SpacemanDMM
        uses: actions/cache@v1
        with:
          path: ~/SpacemanDMM
          key: ${{ runner.os }}-dreamchecker-${{ hashFiles('dependencies.sh')}}
          restore-keys: ${{ runner.os }}-dreamchecker

      - name: Setup Python
        uses: actions/setup-python@v1.2.0

      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1.3.2

      - name: Install Dependencies
        run: |
          tools/ci/install_build_tools.sh
          tools/ci/install_spaceman_dmm.sh dreamchecker

      - name: Run Linter
        id: linter
        run: ~/dreamchecker > ${GITHUB_WORKSPACE}/output-annotations.txt 2>&1

      - name: Annotate Linter
        uses: Yogstation13/DreamAnnotate@v1
        if: always()
        with:
          outputFile: output-annotations.txt

  compile:
    name: Compile
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          curl https://raw.githubusercontent.com/WaspStation/WaspStation-1.0/master/.github/sources.list | sudo tee /etc/apt/sources.list
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt install libstdc++6:i386

      - name: Cache BYOND
        uses: actions/cache@v1
        with:
          path: ~/BYOND
          key: ${{ runner.os }}-byond-${{ hashFiles('Dockerfile')}}
          restore-keys: ${{ runner.os }}-byond

      - name: Setup BYOND
        run: |
          tools/ci/install_byond.sh
          cd $GITHUB_WORKSPACE
          printenv
          echo "::set-env name=BYOND_SYSTEM::/home/runner/BYOND/byond"
          echo "::set-env name=PATH::/home/runner/BYOND/byond/bin:$PATH"
          echo "::set-env name=LD_LIBRARY_PATH::/home/runner/BYOND/byond/bin:$LD_LIBRARY_PATH"
          echo "::set-env name=MANPATH::/home/runner/BYOND/byond/man:$MANPATH"

      - name: Compile
        run: |
          tools/ci/template_dm_generator.py
          tools/ci/dm.sh spacestation13.dme

  test:
    name: Compile and Run
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          curl https://raw.githubusercontent.com/WaspStation/WaspStation-1.0/master/.github/sources.list | sudo tee /etc/apt/sources.list
          sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt install libstdc++6:i386 gcc-multilib g++-7 g++-7-multilib libssl1.1:i386 zlib1g:i386

      - name: Cache BYOND
        uses: actions/cache@v1
        with:
          path: ~/BYOND
          key: ${{ runner.os }}-byond-${{ hashFiles('Dockerfile')}}
          restore-keys: ${{ runner.os }}-byond

      - name: Setup BYOND
        run: |
          tools/ci/install_byond.sh
          cd $GITHUB_WORKSPACE
          printenv
          echo "::set-env name=BYOND_SYSTEM::/home/runner/BYOND/byond"
          echo "::set-env name=PATH::/home/runner/BYOND/byond/bin:$PATH"
          echo "::set-env name=LD_LIBRARY_PATH::/home/runner/BYOND/byond/bin:$LD_LIBRARY_PATH"
          echo "::set-env name=MANPATH::/home/runner/BYOND/byond/man:$MANPATH"

      - name: Compile
        run: |
          tools/ci/template_dm_generator.py
          tools/ci/dm.sh spacestation13.dme

      - name: Prepare Artifacts
        run: |
          mkdir artifacts
          cp spacestation13.dmb artifacts
          cp spacestation13.rsc artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: DMB + RSC
          path: ${{github.workspace}}/artifacts

      - name: Run Server
        run: |
          tools/ci/run_server.sh
