# God help me I'm not good with CI

name: Compile

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
#  lint:
#   name: SpacemanDMM
#    runs-on: ubuntu-18.04
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Cache SpacemanDMM
#        uses: actions/cache@v1
#       with:
#         path: ~/SpacemanDMM
#         key: ${{ runner.os }}-dreamchecker-${{ hashFiles('dependencies.sh')}}
#          restore-keys: ${{ runner.os }}-dreamchecker
#
#     - name: Setup Python
#        uses: actions/setup-python@v1.2.0
#
#      - name: Setup Rust
#        uses: hecrj/setup-rust-action@v1.3.2
#
#      - name: Install Dependencies
#        run: |
#          tools/ci/install_spaceman_dmm.sh dreamchecker
#
#      - name: Run Linter
#        id: linter
#        run: ~/dreamchecker > ${GITHUB_WORKSPACE}/output-annotations.txt 2>&1
#
#      - name: Annotate Linter
#        uses: Yogstation13/DreamAnnotate@v1
#        if: always()
#        with:
#          outputFile: output-annotations.txt

  compile:
    name: Compile
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache BYOND
        uses: actions/cache@v1
        with:
          path: ~/BYOND
          key: ${{ runner.os }}-byond-${{ hashFiles('Dockerfile')}}
          restore-keys: ${{ runner.os }}-byond

      - name: Setup BYOND
        run: |
          tools/ci/install_byond.sh
          cd $GITHUB_WORKSPACE
          printenv
          echo "BYOND_SYSTEM=/home/runner/BYOND/byond" >> $GITHUB_ENV
          echo "/home/runner/BYOND/byond/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/home/runner/BYOND/byond/bin:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "MANPATH=/home/runner/BYOND/byond/man:$MANPATH" >> $GITHUB_ENV

      - name: Compile
        run: |
          tools/ci/dm.sh spacestation13.dme

  test:
    name: Compile and Run
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache BYOND
        uses: actions/cache@v1
        with:
          path: ~/BYOND
          key: ${{ runner.os }}-byond-${{ hashFiles('Dockerfile')}}
          restore-keys: ${{ runner.os }}-byond

      - name: Setup BYOND
        run: |
          tools/ci/install_byond.sh
          cd $GITHUB_WORKSPACE
          printenv
          echo "BYOND_SYSTEM=/home/runner/BYOND/byond" >> $GITHUB_ENV
          echo "/home/runner/BYOND/byond/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/home/runner/BYOND/byond/bin:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "MANPATH=/home/runner/BYOND/byond/man:$MANPATH" >> $GITHUB_ENV

      - name: Compile
        run: |
          tools/ci/dm.sh spacestation13.dme

      - name: Prepare Artifacts
        run: |
          mkdir artifacts
          cp spacestation13.dmb artifacts
          cp spacestation13.rsc artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: DMB + RSC
          path: ${{github.workspace}}/artifacts

      - name: Run Server
        run: |
          tools/ci/run_server.sh
